apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php
  namespace: cloudnative-webapp-adb
spec:
  maxReplicas: 15
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php
  targetCPUUtilizationPercentage: 70
